### PR TITLE
Remove all ADO code from `gei`

### LINKED ISSUE #614: Remove ADO specific args from `gh gei`
Currently all ADO specific args in the `gh gei` are marked as hidden. At some point in the future (lets say a month or so down the road), once customers have had enough time to upgrade, we'll delete the ADO arguments and code paths entirely from `gei`.

## Dependencies
#624

### PR DESCRIPTION
**Pull request by dylan-smith**
- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [ ] Docs updated (or issue created)
- [ ] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

Deletes 1200+ lines of code 🎉 !

⚠️ Must merge #960 before this PR.

A long time ago we used to handle both ADO -> GH and GH -> GH migrations via `gh gei`, but then we split off a separate `gh ado2gh` CLI and moved all the ADO -> GH functionality into `ado2gh` (in Aug 2022). However we left it in `gh gei` also, just made it hidden to preserve compatibility for a while.

That was almost a year ago, and we want to clean up the `gei` code and delete all the ADO functionality from it. HOWEVER, there is ONE ADO related feature that only exists in `gh gei` and NOT `gh ado2gh` and that is the ability to do migrations from ADO Server. This is not something that we officially support, but we added it as a hidden feature to `gh gei` a long time ago to support one specific customer (that still relies on it AFAIK).

PR #960 will add that one missing capability to `gh ado2gh`. Once that ships, then we have to ask that one customer that is using `gh gei` for ADO Server migrations to switch to using `gh ado2gh` instead.  cc @timrogers for customer coordination on this. Then we can merge this PR to complete our cleanup efforts.

Closes #614

### CODE REVIEW

**Review by synthead — APPROVED** [review]
image

**Comment by dylan-smith** [comment]
Gonna wait on @timrogers approval, because I want him to talk to the customer that this impacts before merging it.

**Comment by timrogers** [comment]
We're reaching out to the customer affected by this, and will give them ~2 weeks notice of the change.

**Comment by timrogers** [comment]
We've contacted the customer, and will plan to ship this on June 26.

**Review by timrogers — APPROVED** [review]

**Pull request merged**
