### PR TITLE
Add unit tests for GithubClient

### PR DESCRIPTION
**Pull request by ArinGhazarian**
Closes https://github.com/github/gh-gei/issues/173

This PR adds unit tests for the `GithubClient` class.

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked

### CODE REVIEW

**Comment by dylan-smith** [comment]
you can't use the new namespace with no-braces syntax yet, codeql doesn't support it.

**Comment by ArinGhazarian** [comment]
> you can't use the new namespace with no-braces syntax yet, codeql doesn't support it.

Yeah totally missed that 😞

**Comment by dylan-smith** [comment]
> > you can't use the new namespace with no-braces syntax yet, codeql doesn't support it.
> 
> Yeah totally missed that 😞

really sucks, as it stands today we have to choose between being able to use CodeQL or using C# 10 features. My thought is we can live without C# 10 for a while...but how long do we wait. CodeQL team seems to be targetting CY2022Q1 for it.

**Comment by ArinGhazarian** [comment]
> > > you can't use the new namespace with no-braces syntax yet, codeql doesn't support it.
> > 
> > 
> > Yeah totally missed that 😞
> 
> really sucks, as it stands today we have to choose between being able to use CodeQL or using C# 10 features. My thought is we can live without C# 10 for a while...but how long do we wait. CodeQL team seems to be targetting CY2022Q1 for it.

Well, also in that regard, apparently implicit typing of `Func` and `Action` delegates is a C# 10 feature and not supported by CodeQL yet :(

**Review by dylan-smith — APPROVED** [review]
this all looks great!

**Pull request merged**
