### PR TITLE
Add file newlines

### PR DESCRIPTION
**Pull request by petermeglis**
Updates the editorconfig to enforce file final newlines

- [ ] ~~Did you write/update appropriate tests~~
- [ ] ~~Release notes updated (if appropriate)~~
- [ ] ~~Appropriate logging output~~
- [ ] ~~Issue linked~~

### CODE REVIEW

**Review by ArinGhazarian — COMMENTED** [review]
Why do we need to add these new lines? It certainly doesn't hurt but I don't think it adds any value!

**Comment by dylan-smith** [comment]
> Why do we need to add these new lines? It certainly doesn't hurt but I don't think it adds any value!

I was kinda thinking the same thing

**Comment by petermeglis** [comment]
> > Why do we need to add these new lines? It certainly doesn't hurt but I don't think it adds any value!
> 
> I was kinda thinking the same thing

Because every single PR from now until the end of time will have this icon showing no `\n` at the end of every file changed :)

Screen Shot 2022-02-03 at 1 33 43 PM

**Comment by dylan-smith** [comment]
I'm gonna wait till the e2e PR gets merged in because it's a big one, then I'll come back and update this PR and push it through.

**Comment by petermeglis** [comment]
> I'm gonna wait till the e2e PR gets merged in because it's a big one, then I'll come back and update this PR and push it through.

Sounds good 👍

**Comment by oakeyc** [comment]
>  because it's a big one

If there were any conflicts with this PR, they would be very easy to resolve. You pick your own branch and re-run the formatter! I disagree that there's _no_ value. Linting and formatting is part of code readability and standards.

**Comment by dylan-smith** [comment]
> 



> > because it's a big one
> 
> If there were any conflicts with this PR, they would be very easy to resolve. You pick your own branch and re-run the formatter! I disagree that there's _no_ value. Linting and formatting is part of code readability and standards.

I'm going to merge it because you guys seem to want it, and I don't care either way.

But I will say that we already have linting and formatting and standards. Our current standard  is no EOL char and we have linting to enforce it.

**Pull request merged**
