### PR TITLE
Restructure the folders to one per command

### PR DESCRIPTION
**Pull request by dylan-smith**
No code was meaningfully changed in this PR, it changes our folder structure so instead of folders for Commands/Handlers we now have a folder for each command that contains up to 3 cs files Command/CommandHandler/CommandArgs. As part of this  the xxx.Handlers namespaces went away and everything lives in the Commands namespace.

This PR also split all the CommandArgs classes out into their own files.

Want to get this PR merged in before I come back to the other PR that will refactor the validation to happen in the args classes. 

Both of which are part of the work for #703 

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)

### CODE REVIEW

**Review by ArinGhazarian — CHANGES_REQUESTED** [review]
By convention all namespaces should match the folder structure.

**Comment by dylan-smith** [comment]
> By convention all namespaces should match the folder structure.

Normally I'd agree but I think this is an example where it makes more sense to go against convention. Putting an extra part in the namespace adds no value IMO, the namespace will become redundant with the class name (e.g. OctoshiftCLI.Commands.CreateTeam.CreateTeamCommand) and I wouldn't want to try to remove the name from the class name. Having the folder name match the actual CLI command-name is a useful bit of information when navigating the code structure, and I don't believe you can have hyphens in namespace names so we couldn't make the current folder names namespace names as-is.

**Comment by ArinGhazarian** [comment]
> > By convention all namespaces should match the folder structure.
> 
> 
> 
> Normally I'd agree but I think this is an example where it makes more sense to go against convention. Putting an extra part in the namespace adds no value IMO, the namespace will become redundant with the class name (e.g. OctoshiftCLI.Commands.CreateTeam.CreateTeamCommand) and I wouldn't want to try to remove the name from the class name. Having the folder name match the actual CLI command-name is a useful bit of information when navigating the code structure, and I don't believe you can have hyphens in namespace names so we couldn't make the current folder names match namespace names as-is.

Well I understand your reasoning, but still think following the convention is better. I for example usually don't navigate using the tree explorer but rather do it with the class view explorer and with improper namespacing it'd be very confusing to see the big picture so if we are creating these folders it is going to be confusing to have different namespace structure. Everything else is just fine and it makes sense to keep the class names as is with the command name included. Also I probably haven't noticed but the folder names should also follow the naming guidelines so no hyphen in the names.

**Comment by dylan-smith** [comment]
Superceded by #976

**Pull request closed without merging**
