### PR TITLE
Added: support for session tokens in the AWSAPI factory

### PR DESCRIPTION
**Pull request by mattbryce93**
- [ ] Did you write/update appropriate tests
- [ ] Release notes updated (if appropriate)
- [ ] Appropriate logging output
- [x ] Issue linked
- [ ] Docs updated (or issue created)

### CODE REVIEW

**Comment by dylan-smith** [comment]
Hi @mattbryce93, thanks for trying to contribute! Unfortunately, it looks like your PR needs a lot more work before we could consider accepting it (e.g. it doesn't compile, doesn't pass the linter, I suspect it breaks existing scenarios, and is missing a bunch of things needed to support the STS scenario such as new args).

My best suggestion would be to find a friend that knows a bit more c# to help out, or wait until this backlog item raises to the top of our teams priority list and we can help tackle it.

**Comment by peteraritchie** [comment]
@mattbryce93 is there some code you've added to `EnvironmentVariableProvider` for the `AwsSessionToken()` method you're using in `AwsApiFactory`?

**Comment by dylan-smith** [comment]
FYI there are some discussions going on internally about moving the blob storage configuration into GHES itself instead of passing it into the CLI. If that happens this would become kind of a moot point.

**Comment by ArinGhazarian** [comment]
Closing since this is already done in #844

**Pull request closed without merging**
